### ISSUE TITLE
Django-reversion is incompatible with Wagtail

### ISSUE THREAD

**Issue by nkuttler** [etianen/django-reversion#920]
### Issue Summary

Wagtail and django-revision have conflicting reverse accessors.

```
SystemCheckError: System check identified some issues:

ERRORS:
reversion.Revision.user: (fields.E304) Reverse accessor for 'reversion.Revision.user' clashes with reverse accessor for 'wagtailcore.Revision.user'.
     HINT: Add or change a related_name argument to the definition for 'reversion.Revision.user' or 'wagtailcore.Revision.user'.
wagtailcore.Revision.user: (fields.E304) Reverse accessor for 'wagtailcore.Revision.user' clashes with reverse accessor for 'reversion.Revision.user'.
     HINT: Add or change a related_name argument to the definition for 'wagtailcore.Revision.user' or 'reversion.Revision.user'.
```

### Steps to Reproduce

As far as I can tell simply installing django-reversion and Wagtail together will cause the problem, please let me know if you need help to reproduce this.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.10.5
-   Django version: django==3.2.15
-   Wagtail version: 4.0.1
-   Django-reversion version: 5.0.2
-   Wagtail issue: https://github.com/wagtail/wagtail/issues/9223, previously existing issue: https://github.com/wagtail/wagtail/issues/9158
